/* Generated by Yosys 0.22+4 (git sha1 0e13d7e4c, x86_64-w64-mingw32-g++ 9.2.1 -Os) */

module exe_unit_w15_rtl(i_oper, i_argA, i_argB, i_clk, i_rsn, o_result, o_status);
  input [3:0] i_argA;
  wire [3:0] i_argA;
  input [3:0] i_argB;
  wire [3:0] i_argB;
  input i_clk;
  wire i_clk;
  input [1:0] i_oper;
  wire [1:0] i_oper;
  input i_rsn;
  wire i_rsn;
  output [3:0] o_result;
  wire [3:0] o_result;
  output [2:0] o_status;
  wire [2:0] o_status;
  assign o_result = 4'hx;
  assign o_status = 3'hx;
endmodule
